package proyectodiana;

/**
 *
 * @author WeeDolf
 */
public class RESTAR501 extends javax.swing.JFrame {

    /**
     * Creates new form RESTAR501
     */
    public RESTAR501() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        jColorChooser1 = new javax.swing.JColorChooser();
        jDialog1 = new javax.swing.JDialog();
        jDialog2 = new javax.swing.JDialog();
        jMenu1 = new javax.swing.JMenu();
        jPopupMenu1 = new javax.swing.JPopupMenu();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        jButton17 = new javax.swing.JButton();
        jButton18 = new javax.swing.JButton();
        jButton19 = new javax.swing.JButton();
        jButton20 = new javax.swing.JButton();
        jButton21 = new javax.swing.JButton();
        jButton22 = new javax.swing.JButton();
        jButton23 = new javax.swing.JButton();
        jButton24 = new javax.swing.JButton();
        jButton25 = new javax.swing.JButton();
        jButton26 = new javax.swing.JButton();
        jButton27 = new javax.swing.JButton();
        jButton28 = new javax.swing.JButton();
        jButton29 = new javax.swing.JButton();
        jButton30 = new javax.swing.JButton();
        jButton31 = new javax.swing.JButton();
        jButton32 = new javax.swing.JButton();
        jButton33 = new javax.swing.JButton();
        jButton34 = new javax.swing.JButton();
        jButton35 = new javax.swing.JButton();
        jButton36 = new javax.swing.JButton();
        jButton37 = new javax.swing.JButton();
        jButton38 = new javax.swing.JButton();
        jButton39 = new javax.swing.JButton();
        jButton40 = new javax.swing.JButton();
        jButton41 = new javax.swing.JButton();
        jButton42 = new javax.swing.JButton();
        jButton43 = new javax.swing.JButton();
        jButton44 = new javax.swing.JButton();
        jButton45 = new javax.swing.JButton();
        jButton46 = new javax.swing.JButton();
        jButton47 = new javax.swing.JButton();
        jButton48 = new javax.swing.JButton();
        jButton49 = new javax.swing.JButton();
        jButton50 = new javax.swing.JButton();
        jButton51 = new javax.swing.JButton();
        jButton52 = new javax.swing.JButton();
        jButton53 = new javax.swing.JButton();
        jButton54 = new javax.swing.JButton();
        jButton55 = new javax.swing.JButton();
        jButton56 = new javax.swing.JButton();
        jButton57 = new javax.swing.JButton();
        jButton58 = new javax.swing.JButton();
        jButton59 = new javax.swing.JButton();
        jButton60 = new javax.swing.JButton();
        jButton61 = new javax.swing.JButton();
        jButton62 = new javax.swing.JButton();
        jButton63 = new javax.swing.JButton();
        jButton64 = new javax.swing.JButton();
        jButton65 = new javax.swing.JButton();
        jButton66 = new javax.swing.JButton();
        jButton67 = new javax.swing.JButton();
        jButton68 = new javax.swing.JButton();
        jButton69 = new javax.swing.JButton();
        jButton70 = new javax.swing.JButton();
        jButton71 = new javax.swing.JButton();
        jButton72 = new javax.swing.JButton();
        jButton73 = new javax.swing.JButton();
        jButton74 = new javax.swing.JButton();
        jButton75 = new javax.swing.JButton();
        jButton76 = new javax.swing.JButton();
        jButton77 = new javax.swing.JButton();
        jButton78 = new javax.swing.JButton();
        jButton79 = new javax.swing.JButton();
        jButton80 = new javax.swing.JButton();
        jButton81 = new javax.swing.JButton();
        jButton82 = new javax.swing.JButton();
        jButton83 = new javax.swing.JButton();
        jButton84 = new javax.swing.JButton();
        jButton85 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        areatext = new javax.swing.JTextField();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jDialog2Layout = new javax.swing.GroupLayout(jDialog2.getContentPane());
        jDialog2.getContentPane().setLayout(jDialog2Layout);
        jDialog2Layout.setHorizontalGroup(
            jDialog2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog2Layout.setVerticalGroup(
            jDialog2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        jMenu1.setText("jMenu1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "RESTAR 501", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Andalus", 1, 36), new java.awt.Color(0, 204, 204))); // NOI18N
        jPanel1.setToolTipText("");
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/volver.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 420, 80, 50));

        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 100, 50, 10));

        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 120, 30, 40));

        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 170, 30, 10));

        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 200, 10, 40));

        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 110, 30, 10));

        jButton3.setText("J.1");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 270, 110, -1));

        jButton7.setText("J.2");
        jPanel1.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 270, 110, -1));

        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 130, 30, 30));

        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 180, 20, 10));

        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton11, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 200, 10, 40));

        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton12, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 130, 20, 20));

        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton13, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 150, 30, 30));

        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton14, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 190, 10, 20));

        jButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton15ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton15, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 210, 10, 20));

        jButton16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton16ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton16, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 163, 10, 20));

        jButton17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton17ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton17, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 190, 40, 20));

        jButton18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton18ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton18, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 210, 10, 20));

        jButton19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton19ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton19, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 230, 20, 10));

        jButton20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton20ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton20, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 200, 10, 40));

        jButton21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton21ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton21, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 220, 30, 30));

        jButton22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton22ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton22, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 240, 20, 20));

        jButton23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton23ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton23, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 250, 20, 10));
        jPanel1.add(jButton24, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 250, 10, 50));
        jPanel1.add(jButton25, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 260, 40, 30));
        jPanel1.add(jButton26, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 270, 10, 20));
        jPanel1.add(jButton27, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 270, 40, 10));
        jPanel1.add(jButton28, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 320, 10, 20));
        jPanel1.add(jButton29, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 300, 30, 30));
        jPanel1.add(jButton30, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 300, 20, 20));
        jPanel1.add(jButton31, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 290, 30, 10));
        jPanel1.add(jButton32, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 360, 10, 20));
        jPanel1.add(jButton33, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 340, 30, 30));
        jPanel1.add(jButton34, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 330, 10, 20));
        jPanel1.add(jButton35, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 310, 20, 10));
        jPanel1.add(jButton36, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 410, 20, 10));
        jPanel1.add(jButton37, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 370, 30, 30));
        jPanel1.add(jButton38, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 350, 20, 10));
        jPanel1.add(jButton39, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 310, 10, 20));
        jPanel1.add(jButton40, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 430, 30, 10));
        jPanel1.add(jButton41, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 390, 30, 30));
        jPanel1.add(jButton42, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 370, 20, 10));
        jPanel1.add(jButton43, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 330, 10, 20));
        jPanel1.add(jButton44, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 440, 50, 10));
        jPanel1.add(jButton45, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 393, 30, 40));
        jPanel1.add(jButton46, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 370, 30, 10));
        jPanel1.add(jButton47, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 310, 10, 50));
        jPanel1.add(jButton48, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 430, 30, 10));
        jPanel1.add(jButton49, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 400, 30, 20));
        jPanel1.add(jButton50, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 370, 20, 10));
        jPanel1.add(jButton51, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 320, 10, 30));
        jPanel1.add(jButton52, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 410, 20, 10));
        jPanel1.add(jButton53, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 370, 30, 30));
        jPanel1.add(jButton54, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 350, 20, 10));
        jPanel1.add(jButton55, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 320, 10, 20));
        jPanel1.add(jButton56, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 370, 10, 20));
        jPanel1.add(jButton57, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 340, 30, 30));
        jPanel1.add(jButton58, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 330, 20, -1));
        jPanel1.add(jButton59, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 310, 10, 20));
        jPanel1.add(jButton60, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 310, 10, 30));
        jPanel1.add(jButton61, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 300, 30, 30));
        jPanel1.add(jButton62, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 300, 20, 10));
        jPanel1.add(jButton63, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 290, 20, 10));
        jPanel1.add(jButton64, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 250, 10, 50));
        jPanel1.add(jButton65, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 260, 30, 30));
        jPanel1.add(jButton66, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 260, 10, 30));
        jPanel1.add(jButton67, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 270, 40, 10));
        jPanel1.add(jButton68, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 200, 10, 40));
        jPanel1.add(jButton69, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 220, 30, 30));
        jPanel1.add(jButton70, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 230, 10, 30));

        jButton71.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton71ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton71, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 250, 30, 10));
        jPanel1.add(jButton72, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 170, 10, 20));
        jPanel1.add(jButton73, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 180, 30, 30));
        jPanel1.add(jButton74, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 210, 10, 20));
        jPanel1.add(jButton75, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 230, 20, 10));
        jPanel1.add(jButton76, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 130, 20, 10));
        jPanel1.add(jButton77, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 150, 30, 30));
        jPanel1.add(jButton78, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 190, 10, 20));
        jPanel1.add(jButton79, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 210, 10, 20));
        jPanel1.add(jButton80, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 110, 40, 10));
        jPanel1.add(jButton81, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 130, 30, 30));
        jPanel1.add(jButton82, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 180, 20, 10));
        jPanel1.add(jButton83, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 200, 10, 40));
        jPanel1.add(jButton84, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 250, 30, 10));
        jPanel1.add(jButton85, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 270, 10, 20));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/diana2.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 410, 415));

        areatext.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        areatext.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        areatext.setText("501");
        areatext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                areatextActionPerformed(evt);
            }
        });
        jPanel1.add(areatext, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 180, 110, 60));

        jTextField1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jTextField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField1.setText("501");
        jPanel1.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 180, 110, 60));

        jLabel2.setBackground(new java.awt.Color(0, 204, 204));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText(" MARCADORES");
        jLabel2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 100, 170, 40));

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("VOLVER");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 400, 80, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 830, 490));
        jPanel1.getAccessibleContext().setAccessibleName("");

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
        
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        Menu mn = new Menu();
        mn.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
      int valor;
      int newValor;
      valor = Integer.parseInt(areatext.getText());
      newValor = valor -40;
      areatext.setText(Integer.toString(newValor));
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
      int valor;
      int newValor;
      valor = Integer.parseInt(areatext.getText());
      newValor = valor -20;
      areatext.setText(Integer.toString(newValor));
      
      
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
      int valor;
      int newValor;
      valor = Integer.parseInt(areatext.getText());
      newValor = valor -60;
      areatext.setText(Integer.toString(newValor));
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
      int valor;
      int newValor;
     
     /* if(tengo activado el textarea1){
       valor = Integer.parseInt(areatext.getText());
      newValor = valor -20;
      areatext.setText(Integer.toString(newValor));}
      else 
        areatext2*/
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
    //  INACTIVO ARETEXT2 Y ACTIVO ARETEXT1 . dISABLE 
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton71ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton71ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton71ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
      int valor;
      int newValor;
      valor = Integer.parseInt(areatext.getText());
      newValor = valor -2;
      areatext.setText(Integer.toString(newValor));
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
      int valor;
      int newValor;
      valor = Integer.parseInt(areatext.getText());
      newValor = valor -1;
      areatext.setText(Integer.toString(newValor));
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
      int valor;
      int newValor;
      valor = Integer.parseInt(areatext.getText());
      newValor = valor -3;
      areatext.setText(Integer.toString(newValor));
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
      int valor;
      int newValor;
      valor = Integer.parseInt(areatext.getText());
      newValor = valor -1;
      areatext.setText(Integer.toString(newValor));
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
      int valor;
      int newValor;
      valor = Integer.parseInt(areatext.getText());
      newValor = valor -54;
      areatext.setText(Integer.toString(newValor));
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
      int valor;
      int newValor;
      valor = Integer.parseInt(areatext.getText());
      newValor = valor -18;
      areatext.setText(Integer.toString(newValor));
    }//GEN-LAST:event_jButton13ActionPerformed

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
      int valor;
      int newValor;
      valor = Integer.parseInt(areatext.getText());
      newValor = valor -36;
      areatext.setText(Integer.toString(newValor));
    }//GEN-LAST:event_jButton14ActionPerformed

    private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton15ActionPerformed
      int valor;
      int newValor;
      valor = Integer.parseInt(areatext.getText());
      newValor = valor -18;
      areatext.setText(Integer.toString(newValor));
    }//GEN-LAST:event_jButton15ActionPerformed

    private void jButton16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton16ActionPerformed
      int valor;
      int newValor;
      valor = Integer.parseInt(areatext.getText());
      newValor = valor -12;
      areatext.setText(Integer.toString(newValor));
    }//GEN-LAST:event_jButton16ActionPerformed

    private void jButton17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton17ActionPerformed
      int valor;
      int newValor;
      valor = Integer.parseInt(areatext.getText());
      newValor = valor -4;
      areatext.setText(Integer.toString(newValor));
    }//GEN-LAST:event_jButton17ActionPerformed

    private void jButton18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton18ActionPerformed
      int valor;
      int newValor;
      valor = Integer.parseInt(areatext.getText());
      newValor = valor -8;
      areatext.setText(Integer.toString(newValor));
    }//GEN-LAST:event_jButton18ActionPerformed

    private void jButton19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton19ActionPerformed
      int valor;
      int newValor;
      valor = Integer.parseInt(areatext.getText());
      newValor = valor -4;
      areatext.setText(Integer.toString(newValor));
    }//GEN-LAST:event_jButton19ActionPerformed

    private void jButton20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton20ActionPerformed
      int valor;
      int newValor;
      valor = Integer.parseInt(areatext.getText());
      newValor = valor -39;
      areatext.setText(Integer.toString(newValor));
    }//GEN-LAST:event_jButton20ActionPerformed

    private void jButton21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton21ActionPerformed
      int valor;
      int newValor;
      valor = Integer.parseInt(areatext.getText());
      newValor = valor -13;
      areatext.setText(Integer.toString(newValor));
    }//GEN-LAST:event_jButton21ActionPerformed

    private void jButton22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton22ActionPerformed
      int valor;
      int newValor;
      valor = Integer.parseInt(areatext.getText());
      newValor = valor -26;
      areatext.setText(Integer.toString(newValor));
    }//GEN-LAST:event_jButton22ActionPerformed

    private void jButton23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton23ActionPerformed
      int valor;
      int newValor;
      valor = Integer.parseInt(areatext.getText());
      newValor = valor -13;
      areatext.setText(Integer.toString(newValor));
    }//GEN-LAST:event_jButton23ActionPerformed

    private void areatextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_areatextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_areatextActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RESTAR501.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RESTAR501.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RESTAR501.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RESTAR501.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RESTAR501().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField areatext;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton19;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton20;
    private javax.swing.JButton jButton21;
    private javax.swing.JButton jButton22;
    private javax.swing.JButton jButton23;
    private javax.swing.JButton jButton24;
    private javax.swing.JButton jButton25;
    private javax.swing.JButton jButton26;
    private javax.swing.JButton jButton27;
    private javax.swing.JButton jButton28;
    private javax.swing.JButton jButton29;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton30;
    private javax.swing.JButton jButton31;
    private javax.swing.JButton jButton32;
    private javax.swing.JButton jButton33;
    private javax.swing.JButton jButton34;
    private javax.swing.JButton jButton35;
    private javax.swing.JButton jButton36;
    private javax.swing.JButton jButton37;
    private javax.swing.JButton jButton38;
    private javax.swing.JButton jButton39;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton40;
    private javax.swing.JButton jButton41;
    private javax.swing.JButton jButton42;
    private javax.swing.JButton jButton43;
    private javax.swing.JButton jButton44;
    private javax.swing.JButton jButton45;
    private javax.swing.JButton jButton46;
    private javax.swing.JButton jButton47;
    private javax.swing.JButton jButton48;
    private javax.swing.JButton jButton49;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton50;
    private javax.swing.JButton jButton51;
    private javax.swing.JButton jButton52;
    private javax.swing.JButton jButton53;
    private javax.swing.JButton jButton54;
    private javax.swing.JButton jButton55;
    private javax.swing.JButton jButton56;
    private javax.swing.JButton jButton57;
    private javax.swing.JButton jButton58;
    private javax.swing.JButton jButton59;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton60;
    private javax.swing.JButton jButton61;
    private javax.swing.JButton jButton62;
    private javax.swing.JButton jButton63;
    private javax.swing.JButton jButton64;
    private javax.swing.JButton jButton65;
    private javax.swing.JButton jButton66;
    private javax.swing.JButton jButton67;
    private javax.swing.JButton jButton68;
    private javax.swing.JButton jButton69;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton70;
    private javax.swing.JButton jButton71;
    private javax.swing.JButton jButton72;
    private javax.swing.JButton jButton73;
    private javax.swing.JButton jButton74;
    private javax.swing.JButton jButton75;
    private javax.swing.JButton jButton76;
    private javax.swing.JButton jButton77;
    private javax.swing.JButton jButton78;
    private javax.swing.JButton jButton79;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton80;
    private javax.swing.JButton jButton81;
    private javax.swing.JButton jButton82;
    private javax.swing.JButton jButton83;
    private javax.swing.JButton jButton84;
    private javax.swing.JButton jButton85;
    private javax.swing.JButton jButton9;
    private javax.swing.JColorChooser jColorChooser1;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JDialog jDialog2;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
